/**
 * @file provenance.types.ts
 * @description Core TypeScript types for the Nexora Digital Content
 *              Provenance & Authenticity Verification Platform.
 *
 * These types are shared between:
 *   - Frontend (Next.js components, hooks)
 *   - API Route Handlers (register/route.ts, verify/route.ts)
 *   - Future: AI explanation service, blockchain anchoring hooks
 *
 * Mirrors the Supabase `assets` table schema and the on-chain
 * `ProvenanceRegistry` contract's data structures.
 */

// ─── Tamper Classification ────────────────────────────────────────────────────

/**
 * The result of comparing a perceptual hash (aHash) against the registered
 * original using Hamming Distance.
 *
 * Ordered from most similar to least similar:
 *   IDENTICAL        → 0 bits differ          (exact visual match)
 *   LIKELY_ORIGINAL  → 1–10 bits differ       (recompression, noise)
 *   MINOR_EDIT       → 11–20 bits differ      (crop, brightness)
 *   TAMPERED         → 21–40 bits differ      (significant alteration)
 *   HEAVILY_TAMPERED → >40 bits differ        (major modification)
 */
export type TamperLevel =
  | "IDENTICAL"
  | "LIKELY_ORIGINAL"
  | "MINOR_EDIT"
  | "TAMPERED"
  | "HEAVILY_TAMPERED";

// ─── Verification Status ──────────────────────────────────────────────────────

/**
 * The outcome of a verification request against the provenance registry.
 *
 *   VERIFIED_ORIGINAL → SHA-256 exact match found — file is byte-identical to original.
 *   LIKELY_TAMPERED   → aHash fuzzy match found within threshold — visually similar
 *                        but not identical; probable tampering.
 *   NOT_REGISTERED    → No match found by either method — no provenance record exists.
 */
export type VerificationStatus =
  | "VERIFIED_ORIGINAL"
  | "LIKELY_TAMPERED"
  | "NOT_REGISTERED";

// ─── Asset Record ─────────────────────────────────────────────────────────────

/**
 * Represents a registered digital asset.
 *
 * Maps directly to a row in the Supabase `assets` table.
 * The `sha256` is what gets anchored on-chain in the `ProvenanceRegistry` contract.
 *
 * On-chain anchor fields are nullable — they are populated by POST /api/anchor
 * after a successful anchorHash() transaction on Monad Testnet.
 */
export interface Asset {
  /** UUID primary key, generated by Supabase. */
  id: string;

  /** Original filename at time of upload (e.g., "press-release-photo.jpg"). */
  filename: string;

  /**
   * Path within the "assets" Supabase Storage bucket.
   * Format: `originals/{uuid}.{ext}`
   */
  storagePath: string;

  /**
   * SHA-256 cryptographic hash of the raw file bytes (64 hex chars).
   * This is the canonical identity of the asset.
   * MUST match what is anchored on-chain in `ProvenanceRegistry`.
   */
  sha256: string;

  /**
   * Perceptual average hash of the image (64 hex chars for 16×16 aHash).
   * Used for fuzzy tamper detection via Hamming Distance comparison.
   */
  ahash: string;

  /** Original image width in pixels. Null if Sharp could not determine. */
  width: number | null;

  /** Original image height in pixels. Null if Sharp could not determine. */
  height: number | null;

  /** File size of the original upload in bytes. */
  fileSize: number;

  /**
   * Public CDN URL to the original image in Supabase Storage.
   * Constructed via `getPublicStorageUrl()` in supabase.ts.
   */
  imageUrl: string;

  /** ISO 8601 timestamp of when this asset was first registered. */
  registeredAt: string;

  // ── On-chain anchor fields (nullable until anchored) ─────────────────────

  /**
   * 0x-prefixed Monad Testnet transaction hash from the anchorHash() call.
   * Null until the asset has been anchored via POST /api/anchor.
   */
  txHash: string | null;

  /**
   * Address of the ProvenanceRegistry contract that anchored this asset.
   * Null until anchored. Stored for auditability across contract upgrades.
   */
  contractAddress: string | null;

  /**
   * ISO 8601 timestamp of when the on-chain anchor transaction was mined.
   * Null until anchored.
   */
  anchoredAt: string | null;
}

// ─── Anchor Record ────────────────────────────────────────────────────────────

/**
 * Represents an on-chain provenance anchor written to the
 * `ProvenanceRegistry` smart contract on Monad Testnet.
 *
 * Written by the `anchorHash(bytes32 contentHash)` contract function
 * after a successful registration.
 */
export interface AnchorRecord {
  /** The SHA-256 hash of the asset, stored as a bytes32 on-chain. */
  contentHash: `0x${string}`;

  /**
   * The Ethereum address of the wallet that anchored this hash.
   * Serves as the on-chain proof of origin.
   */
  anchoredBy: `0x${string}`;

  /** Unix timestamp (seconds) from the block in which the anchor was mined. */
  anchoredAt: number;

  /**
   * The transaction hash of the `anchorHash()` call on Monad Testnet.
   * Use this to link to the block explorer for the demo.
   */
  txHash: `0x${string}`;

  /** The Monad Testnet block number in which the anchor transaction was mined. */
  blockNumber: bigint;
}

// ─── Verification Result ──────────────────────────────────────────────────────

/**
 * The complete result returned by POST /api/verify.
 *
 * Uses a discriminated union on `status` so TypeScript can narrow the type
 * and guarantee field access safety in the consuming UI code.
 *
 * @example
 * const result: VerificationResult = await verifyAsset(file);
 * if (result.status === "VERIFIED_ORIGINAL") {
 *   console.log(result.matchedAsset.sha256); // ✅ TypeScript knows this exists
 * }
 * if (result.status === "LIKELY_TAMPERED") {
 *   console.log(result.hammingDistance);     // ✅ TypeScript knows this exists
 * }
 * if (result.status === "NOT_REGISTERED") {
 *   // result has no extra fields — image has no provenance record
 * }
 */
export type VerificationResult =
  | VerifiedOriginalResult
  | LikelyTamperedResult
  | NotRegisteredResult;

/** Returned when the uploaded file is a byte-identical copy of the registered original. */
export interface VerifiedOriginalResult {
  status: "VERIFIED_ORIGINAL";

  /** UUID of the matched asset record in the database. */
  assetId: string;

  /** SHA-256 that matched, for display and on-chain cross-reference. */
  sha256: string;

  /** The full matched asset record from the provenance database. */
  matchedAsset: Asset;
}

/** Returned when the image is visually similar but not byte-identical — probable tampering. */
export interface LikelyTamperedResult {
  status: "LIKELY_TAMPERED";

  /** UUID of the closest matched asset record. */
  assetId: string;

  /** Number of bits that differ between the uploaded and registered aHash (0–256). */
  hammingDistance: number;

  /** Similarity expressed as a percentage (0.0–100.0). */
  similarityPercent: number;

  /** Machine-readable tamper severity classification from hammingDistance.ts. */
  tamperLevel: TamperLevel;

  /**
   * Human-readable description of what the tamper level means.
   * Suitable for direct display in the UI or as AI prompt context.
   */
  tamperDescription: string;

  /** The asset that was the closest match in the registry. */
  matchedAsset: Asset;
}

/** Returned when no registered asset matches the upload by SHA-256 or aHash. */
export interface NotRegisteredResult {
  status: "NOT_REGISTERED";
}

// ─── Registration Result ──────────────────────────────────────────────────────

/**
 * Returned by POST /api/register on successful asset registration.
 * Contains the hashes needed for on-chain anchoring and QR code generation.
 */
export interface RegistrationResult {
  /** UUID of the newly created (or pre-existing duplicate) asset record. */
  assetId: string;

  /** SHA-256 of the file — anchor this on Monad via `ProvenanceRegistry.anchorHash()`. */
  sha256: string;

  /** Perceptual hash for future fuzzy verification. */
  ahash: string;

  /** Public CDN URL to view the registered image. */
  imageUrl: string;
}
