/**
 * @file hammingDistance.ts
 * @description Computes the Hamming Distance between two perceptual hash strings.
 *
 * WHAT IS HAMMING DISTANCE?
 * The Hamming Distance between two binary strings of equal length is simply the
 * number of bit positions where the two strings DIFFER.
 *
 * Example:
 *   Hash A: 1001 1010  (binary)
 *   Hash B: 1101 1000  (binary)
 *   XOR:    0100 0010  ← bits that differ
 *   Hamming Distance = 2 (two bit positions differ)
 *
 * HOW WE APPLY IT TO HEX HASHES:
 * Our perceptual hashes (from averageHash.ts) are 64-character hex strings,
 * each character representing 4 bits (a nibble). We convert each hex character
 * to a 4-bit number, XOR the two values, and count the set bits in the result
 * using a popcount (population count) lookup table for performance.
 *
 * INTERPRETING THE RESULT (for a 256-bit hash):
 * ┌────────────────────┬───────────────────────────────────────────────┐
 * │ Distance (bits)    │ Interpretation                                │
 * ├────────────────────┼───────────────────────────────────────────────┤
 * │ 0                  │ Identical images (or exact duplicate)         │
 * │ 1 – 10             │ Nearly identical (recompressed, minor noise)  │
 * │ 11 – 20            │ Similar but likely edited (brightness/crop)   │
 * │ 21 – 40            │ Moderate difference, probable tampering       │
 * │ > 40               │ Significantly different, likely tampered      │
 * │ ~128               │ Completely unrelated images (random chance)   │
 * └────────────────────┴───────────────────────────────────────────────┘
 *
 * Use Case in Veritas:
 *   - Compare the perceptual hash of an uploaded image against the hash stored
 *     on-chain (fetched from Monad Testnet via Viem).
 *   - Use the distance to CLASSIFY the result and feed a meaningful tamper
 *     report to the AI explanation service.
 */

/**
 * Precomputed lookup table for the number of set bits (popcount) in a 4-bit
 * nibble (0–15). This avoids calling a loop for every nibble during comparison.
 *
 * Index = the nibble value (0–15)
 * Value = number of 1-bits in that nibble's binary representation
 *
 * Examples:
 *   POPCOUNT_NIBBLE[0]  = 0  (0000 → 0 ones)
 *   POPCOUNT_NIBBLE[5]  = 2  (0101 → 2 ones)
 *   POPCOUNT_NIBBLE[15] = 4  (1111 → 4 ones)
 */
const POPCOUNT_NIBBLE: readonly number[] = [
  0, // 0  = 0000
  1, // 1  = 0001
  1, // 2  = 0010
  2, // 3  = 0011
  1, // 4  = 0100
  2, // 5  = 0101
  2, // 6  = 0110
  3, // 7  = 0111
  1, // 8  = 1000
  2, // 9  = 1001
  2, // 10 = 1010
  3, // 11 = 1011
  2, // 12 = 1100
  3, // 13 = 1101
  3, // 14 = 1110
  4, // 15 = 1111
] as const;

/**
 * Represents the result of a perceptual hash comparison, providing both
 * the raw bit distance and a human-readable tamper classification.
 */
export interface HammingResult {
  /** The number of bits that differ between the two hashes (0 to hashBits). */
  distance: number;

  /** The total number of bits compared (e.g., 256 for a 64-char hex hash). */
  totalBits: number;

  /**
   * The similarity expressed as a percentage (0.0 to 100.0).
   * 100.0 = identical, 0.0 = completely different.
   */
  similarityPercent: number;

  /**
   * A human-readable classification of the tamper status based on the distance.
   * Used directly in the AI explanation prompt and the frontend UI badge.
   */
  tamperLevel: "IDENTICAL" | "LIKELY_ORIGINAL" | "MINOR_EDIT" | "TAMPERED" | "HEAVILY_TAMPERED";

  /**
   * A brief, plain-English description of what the distance means.
   * Suitable for display in the UI or inclusion in the AI prompt.
   */
  description: string;
}

/**
 * Computes the Hamming Distance between two perceptual hash hex strings
 * and returns a structured result with similarity metrics and tamper classification.
 *
 * Both hashes must be lowercase hexadecimal strings of equal length. They should
 * be generated by the same hashing algorithm and the same parameters (e.g., both
 * 64-character strings from `computeAverageHash()`).
 *
 * @param {string} hashA - The ORIGINAL hash (e.g., retrieved from on-chain storage).
 * @param {string} hashB - The NEW/UPLOADED hash to compare against the original.
 * @returns {HammingResult} A structured result object with distance, similarity,
 *                          and a tamper classification.
 * @throws {TypeError} If either argument is not a non-empty string.
 * @throws {Error} If the two hashes have different lengths.
 * @throws {Error} If either hash contains non-hexadecimal characters.
 *
 * @example
 * import { computeHammingDistance } from "@/lib/hash/hammingDistance";
 *
 * const original = "f8f0e0c0808080807f7f1f0f070301ff"; // from on-chain
 * const uploaded  = "f8f0e0c0808080007f7f1f0f070301ef"; // newly uploaded
 *
 * const result = computeHammingDistance(original, uploaded);
 * console.log(result.distance);         // => 3
 * console.log(result.similarityPercent); // => 98.83
 * console.log(result.tamperLevel);      // => "LIKELY_ORIGINAL"
 */
export function computeHammingDistance(hashA: string, hashB: string): HammingResult {
  // --- Input Validation ---

  // Ensure both arguments are non-empty strings before proceeding.
  if (typeof hashA !== "string" || hashA.length === 0) {
    throw new TypeError(
      `[hammingDistance] 'hashA' must be a non-empty hex string. ` +
      `Received: ${JSON.stringify(hashA)}`
    );
  }
  if (typeof hashB !== "string" || hashB.length === 0) {
    throw new TypeError(
      `[hammingDistance] 'hashB' must be a non-empty hex string. ` +
      `Received: ${JSON.stringify(hashB)}`
    );
  }

  // Normalize to lowercase to avoid case-sensitivity issues (e.g., "FF" vs "ff").
  const normalizedA = hashA.toLowerCase();
  const normalizedB = hashB.toLowerCase();

  // The two hashes must be the same length to compare them bit-by-bit.
  if (normalizedA.length !== normalizedB.length) {
    throw new Error(
      `[hammingDistance] Hash length mismatch. ` +
      `hashA has ${normalizedA.length} characters but hashB has ${normalizedB.length}. ` +
      `Both hashes must be generated with the same algorithm and parameters.`
    );
  }

  // Validate that both strings are valid hexadecimal (contain only 0-9, a-f).
  const hexPattern = /^[0-9a-f]+$/;
  if (!hexPattern.test(normalizedA)) {
    throw new Error(
      `[hammingDistance] 'hashA' contains non-hexadecimal characters: "${hashA}". ` +
      `Only 0-9 and a-f are valid.`
    );
  }
  if (!hexPattern.test(normalizedB)) {
    throw new Error(
      `[hammingDistance] 'hashB' contains non-hexadecimal characters: "${hashB}". ` +
      `Only 0-9 and a-f are valid.`
    );
  }

  // --- Hamming Distance Computation ---

  // Each hex character = 4 bits (a nibble). Total bits = hex chars * 4.
  const totalBits = normalizedA.length * 4;

  let distance = 0;

  for (let i = 0; i < normalizedA.length; i++) {
    // Parse each hex character to its integer nibble value (0–15).
    // `parseInt(char, 16)` converts a single hex char to a number in base 16.
    const nibbleA = parseInt(normalizedA[i], 16);
    const nibbleB = parseInt(normalizedB[i], 16);

    // XOR the two nibbles: the result has a 1-bit wherever the two differ.
    // Example: nibbleA = 0b1100 (12), nibbleB = 0b1010 (10)
    //          XOR      = 0b0110 (6)  ← bits 1 and 2 differ
    const xorResult = nibbleA ^ nibbleB;

    // Count the number of set bits (1s) in the XOR result using the lookup table.
    // This avoids a per-bit loop and is O(1) per nibble.
    distance += POPCOUNT_NIBBLE[xorResult];
  }

  // --- Compute Derived Metrics ---

  // Similarity as a percentage: 0 distance = 100%, max distance = 0%.
  const similarityPercent = parseFloat(
    (((totalBits - distance) / totalBits) * 100).toFixed(2)
  );

  // --- Classify the Tamper Level ---
  // Thresholds are tuned for a 256-bit hash (64 hex chars). If you change
  // HASH_SIZE in averageHash.ts, you must re-tune these thresholds proportionally.
  const tamperLevel = classifyTamperLevel(distance, totalBits);
  const description = buildDescription(tamperLevel, distance, totalBits);

  return {
    distance,
    totalBits,
    similarityPercent,
    tamperLevel,
    description,
  };
}

// ---------------------------------------------------------------------------
// Private Helpers
// ---------------------------------------------------------------------------

/**
 * Classifies the tamper level based on the Hamming distance and total bit count.
 *
 * Thresholds are expressed as a fraction of total bits to remain correct even
 * if the hash size changes (e.g., a future upgrade from 256-bit to 512-bit).
 *
 * @param distance - Number of differing bits.
 * @param totalBits - Total number of bits in the hash.
 * @returns {HammingResult["tamperLevel"]} The tamper classification.
 */
function classifyTamperLevel(
  distance: number,
  totalBits: number
): HammingResult["tamperLevel"] {
  // Express distance as a fraction of total bits for threshold independence.
  const ratio = distance / totalBits;

  if (distance === 0) {
    return "IDENTICAL";        // 0%   — bit-perfect match
  } else if (ratio <= 0.039) {
    return "LIKELY_ORIGINAL";  // ≤ ~10 bits for 256-bit — noise/recompression
  } else if (ratio <= 0.078) {
    return "MINOR_EDIT";       // ≤ ~20 bits for 256-bit — brightness, minor crop
  } else if (ratio <= 0.156) {
    return "TAMPERED";         // ≤ ~40 bits for 256-bit — significant modification
  } else {
    return "HEAVILY_TAMPERED"; // > 40 bits for 256-bit — majorly different image
  }
}

/**
 * Generates a plain-English description of the tamper level for use in the
 * frontend UI and as context for the AI explanation prompt.
 *
 * @param level - The tamper classification.
 * @param distance - Number of differing bits.
 * @param totalBits - Total number of bits in the hash.
 * @returns {string} A human-readable description string.
 */
function buildDescription(
  level: HammingResult["tamperLevel"],
  distance: number,
  totalBits: number
): string {
  switch (level) {
    case "IDENTICAL":
      return (
        `The image is a perfect match. No bits differ (${distance}/${totalBits}). ` +
        `This is either the exact original file or a byte-identical copy.`
      );
    case "LIKELY_ORIGINAL":
      return (
        `The image is visually nearly identical to the registered original ` +
        `(${distance}/${totalBits} bits differ). The small difference is likely due to ` +
        `file re-compression (e.g., JPEG quality changes) or minor metadata variation. ` +
        `The content appears authentic.`
      );
    case "MINOR_EDIT":
      return (
        `The image shows minor visual differences from the registered original ` +
        `(${distance}/${totalBits} bits differ). This could indicate a slight crop, ` +
        `brightness or contrast adjustment, or a format conversion. ` +
        `Manual review is recommended.`
      );
    case "TAMPERED":
      return (
        `Significant visual differences detected (${distance}/${totalBits} bits differ). ` +
        `The image has likely been meaningfully altered — e.g., objects added/removed, ` +
        `substantial cropping, or color manipulation. This content should be flagged ` +
        `as potentially tampered.`
      );
    case "HEAVILY_TAMPERED":
      return (
        `Severe visual differences detected (${distance}/${totalBits} bits differ). ` +
        `The image is largely unrecognizable as the registered original. ` +
        `This is a strong indicator of deliberate tampering or that a completely ` +
        `different image has been submitted for verification.`
      );
    default: {
      // TypeScript exhaustiveness check — this code path should never be reached.
      const _exhaustive: never = level;
      return `Unknown tamper level: ${_exhaustive}`;
    }
  }
}
