/**
 * @file supabase.ts
 * @description Supabase client factory and type definitions for Nexora.
 *
 * ARCHITECTURE NOTE — TWO CLIENTS:
 * Supabase requires different client configurations depending on the runtime context:
 *
 *   1. `createBrowserClient` — for React components (client-side).
 *      Reads the anon key and persists the session in localStorage.
 *
 *   2. `createServerClient` — for Next.js Route Handlers & Server Components.
 *      For our upload/verify API routes, we use the SERVICE ROLE KEY, which
 *      bypasses Row Level Security (RLS). This is intentional for a backend
 *      API route that runs on the server and should never be exposed to the browser.
 *
 * ENVIRONMENT VARIABLES REQUIRED (.env.local):
 *   NEXT_PUBLIC_SUPABASE_URL      — Your project URL (safe to expose to browser)
 *   NEXT_PUBLIC_SUPABASE_ANON_KEY — Public anon key (safe to expose to browser)
 *   SUPABASE_SERVICE_ROLE_KEY     — Secret service role key (SERVER ONLY, never expose)
 *
 * SUPABASE SETUP CHECKLIST:
 *   1. Create a Storage bucket named "assets" (set to public for read access).
 *   2. Create the `assets` table using the schema defined in `AssetRecord` below.
 *   3. (Optional) Enable RLS on `assets` if you add user authentication later.
 *
 * SQL to create the assets table:
 * ─────────────────────────────────────────────────────────────────────────────
 * CREATE TABLE assets (
 *   id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 *   filename     TEXT NOT NULL,
 *   storage_path TEXT NOT NULL UNIQUE,
 *   sha256       TEXT NOT NULL UNIQUE,
 *   ahash        TEXT NOT NULL,
 *   width        INTEGER,
 *   height       INTEGER,
 *   file_size    INTEGER NOT NULL,
 *   created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { createClient, type SupabaseClient } from "@supabase/supabase-js";

// ─── Environment Variable Validation ─────────────────────────────────────────
// Validate at module load time so misconfiguration fails loudly at startup,
// not silently at runtime during an actual request.

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://placeholder.supabase.co";
const SUPABASE_ANON_KEY = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || "placeholder_anon_key";
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!process.env.NEXT_PUBLIC_SUPABASE_URL || !process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY) {
  console.warn("[supabase] ⚠ Missing Supabase env vars. Using placeholders (will fail at runtime).");
}

// ─── Database Types ───────────────────────────────────────────────────────────

/**
 * Represents a single row in the `assets` Supabase table.
 * Maps directly to the SQL schema defined above.
 *
 * On-chain anchor columns (nullable — populated by POST /api/anchor):
 *   tx_hash          — Monad Testnet transaction hash from anchorHash() call
 *   contract_address — Address of the ProvenanceRegistry contract
 *   anchored_at      — ISO 8601 timestamp of when the anchor tx was mined
 */
export interface AssetRecord {
  /** UUID primary key, generated by Supabase (gen_random_uuid()). */
  id: string;

  /** Original filename from the upload (e.g., "photo.jpg"). */
  filename: string;

  /**
   * The full path within the "assets" Supabase Storage bucket.
   * Format: `originals/{uuid}.{ext}` (e.g., "originals/a1b2c3d4.jpg")
   * Use this with `supabase.storage.from("assets").getPublicUrl(storage_path)`.
   */
  storage_path: string;

  /**
   * SHA-256 cryptographic hash of the raw file buffer (hex string, 64 chars).
   * Used for exact tamper detection — any byte change produces a different hash.
   */
  sha256: string;

  /**
   * Average perceptual hash of the image (hex string, 64 chars for 16x16 aHash).
   * Used for fuzzy/visual similarity detection via Hamming distance.
   */
  ahash: string;

  /** Width of the original image in pixels, from Sharp metadata. */
  width: number | null;

  /** Height of the original image in pixels, from Sharp metadata. */
  height: number | null;

  /** File size of the original upload in bytes. */
  file_size: number;

  /** ISO 8601 timestamp of when this asset was registered. */
  created_at: string;

  /**
   * 0x-prefixed Monad Testnet transaction hash from the anchorHash() call.
   * Null until the asset has been anchored via POST /api/anchor.
   */
  tx_hash: string | null;

  /**
   * Address of the deployed ProvenanceRegistry contract that anchored this asset.
   * Null until anchored. Stored for auditability (contract upgrades).
   */
  contract_address: string | null;

  /**
   * ISO 8601 timestamp of when the on-chain anchor transaction was mined.
   * Null until anchored.
   */
  anchored_at: string | null;
}

/**
 * Input type for inserting a new row into the `assets` table.
 * Omits `id`, `created_at`, and anchor columns (tx_hash, contract_address,
 * anchored_at) because:
 *   - id & created_at are generated by Supabase automatically.
 *   - Anchor columns are nullable and default to NULL in PostgreSQL;
 *     we must NOT send them on insert or Supabase's schema cache will
 *     reject the insert if the ALTER TABLE migration has not been applied
 *     yet (PGRST204 error). They are written later by POST /api/anchor.
 */
export type AssetInsert = Omit<AssetRecord, "id" | "created_at" | "tx_hash" | "contract_address" | "anchored_at">;

// ─── Anchor Record (on-chain) ─────────────────────────────────────────────────

/**
 * Represents a row in the `anchors` Supabase table.
 *
 * Written by POST /api/anchor after a successful on-chain anchorHash() call.
 * Links a registered asset (assets.id) to its Monad Testnet transaction.
 *
 * SQL to create the anchors table:
 * ─────────────────────────────────────────────────────────────────────────────
 * CREATE TABLE anchors (
 *   id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
 *   asset_id     UUID NOT NULL REFERENCES assets(id) ON DELETE CASCADE,
 *   chain_hash   TEXT NOT NULL,
 *   tx_hash      TEXT NOT NULL UNIQUE,
 *   block_number BIGINT NOT NULL,
 *   anchored_by  TEXT NOT NULL,
 *   chain_id     INTEGER NOT NULL,
 *   created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
 * );
 * CREATE INDEX anchors_asset_id_idx ON anchors(asset_id);
 * CREATE INDEX anchors_chain_hash_idx ON anchors(chain_hash);
 * ─────────────────────────────────────────────────────────────────────────────
 */
export interface AnchorRecord {
  /** UUID primary key, generated by Supabase. */
  id: string;

  /** Foreign key to assets.id — which asset this anchor belongs to. */
  asset_id: string;

  /**
   * The SHA-256 hex string that was converted to bytes32 and sent on-chain.
   * Matches assets.sha256 for the linked asset.
   */
  chain_hash: string;

  /** The 0x-prefixed transaction hash from the Monad Testnet anchorHash() call. */
  tx_hash: string;

  /** The block number in which the anchor transaction was mined. */
  block_number: number;

  /** The wallet address (0x-prefixed) that signed and submitted the transaction. */
  anchored_by: string;

  /** Monad Testnet chain ID (e.g., 10143 for Monad Testnet). */
  chain_id: number;

  /** ISO 8601 timestamp of when this record was written to Supabase. */
  created_at: string;
}

/**
 * Input type for inserting a new anchor row.
 * Omits `id` and `created_at` since Supabase generates these.
 */
export type AnchorInsert = Omit<AnchorRecord, "id" | "created_at">;

/**
 * The full typed database schema, used as the generic parameter for
 * `createClient<Database>()`. Includes the `assets` and `anchors` tables.
 */
export interface Database {
  public: {
    Tables: {
      assets: {
        Row:    AssetRecord;
        Insert: AssetInsert;
        /**
         * Update type allows partial updates.
         * Anchor columns (tx_hash, contract_address, anchored_at) are
         * written via a targeted UPDATE in POST /api/anchor.
         */
        Update: Partial<AssetInsert>;
      };
      anchors: {
        Row:    AnchorRecord;
        Insert: AnchorInsert;
        Update: Partial<AnchorInsert>;
      };
    };
    Views:          Record<string, never>;
    Functions:      Record<string, never>;
    Enums:          Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
}

// ─── Supabase Storage Constants ───────────────────────────────────────────────

/**
 * The name of the Supabase Storage bucket where original images are stored.
 * Must be created manually in the Supabase dashboard before use.
 */
export const STORAGE_BUCKET = "assets" as const;

/**
 * The folder prefix inside the bucket where original (unmodified) uploads live.
 * Keeping originals in a subfolder makes it easy to add `/thumbnails` later.
 */
export const STORAGE_FOLDER_ORIGINALS = "originals" as const;

// ─── Client Instances ─────────────────────────────────────────────────────────

/**
 * A Supabase client for use in React components (browser context).
 *
 * Uses the PUBLIC anon key. Subject to Row Level Security (RLS) policies.
 * Safe to use on the client — the anon key is intentionally public.
 *
 * @example
 * import { supabaseBrowser } from "@/lib/supabase";
 * const { data } = await supabaseBrowser.from("assets").select("*");
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabaseBrowser: SupabaseClient<any, "public", any> = createClient<any, "public", any>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: false,
      autoRefreshToken: false,
    },
  }
);

/**
 * Creates a Supabase admin client for use in Next.js Route Handlers
 * and Server Components ONLY.
 *
 * Uses the SERVICE ROLE KEY which bypasses RLS entirely. This is appropriate
 * for our API routes because they are server-side and not accessible to the browser.
 *
 * ⚠️  NEVER import this function or the SERVICE ROLE KEY in any client component.
 *     NEVER expose SUPABASE_SERVICE_ROLE_KEY to the browser (no NEXT_PUBLIC_ prefix).
 *
 * We use a factory function (not a singleton) because Next.js Route Handlers
 * can run across multiple edge instances where shared module-level state is unsafe.
 *
 * @returns {SupabaseClient<any, "public", any>} An admin Supabase client instance.
 * @throws {Error} If SUPABASE_SERVICE_ROLE_KEY is not set in the environment.
 *
 * @example
 * // src/app/api/register/route.ts
 * import { createAdminClient } from "@/lib/supabase";
 * const supabase = createAdminClient();
 * const { data, error } = await supabase.from("assets").insert([...]);
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export function createAdminClient(): SupabaseClient<any, "public", any> {
  if (!SUPABASE_SERVICE_ROLE_KEY) {
    throw new Error(
      "[supabase] Missing env var: SUPABASE_SERVICE_ROLE_KEY. " +
      "This key is required for server-side API routes. " +
      "Add it to .env.local and NEVER expose it to the browser."
    );
  }

  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  return createClient<any, "public", any>(SUPABASE_URL!, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      // Server-side clients should never persist sessions or auto-refresh tokens.
      // Each Route Handler invocation is stateless.
      persistSession: false,
      autoRefreshToken: false,
    },
  });
}

/**
 * Constructs the public HTTPS URL for a file in the "assets" Storage bucket.
 *
 * Uses `getPublicUrl()` which returns a URL synchronously without a network call.
 * The bucket must be set to PUBLIC in the Supabase dashboard for this URL to work.
 *
 * @param {SupabaseClient<Database>} client - A Supabase client instance.
 * @param {string} storagePath - The path within the bucket (e.g., "originals/abc.jpg").
 * @returns {string} The full public URL to the file.
 *
 * @example
 * const url = getPublicStorageUrl(supabase, "originals/abc123.jpg");
 * // => "https://xyz.supabase.co/storage/v1/object/public/assets/originals/abc123.jpg"
 */
export function getPublicStorageUrl(
  client: SupabaseClient<Database>,
  storagePath: string
): string {
  const { data } = client.storage.from(STORAGE_BUCKET).getPublicUrl(storagePath);
  return data.publicUrl;
}
